import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#1E4F91",
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: "700",
    color: "#fff",
    letterSpacing: 1,
  },
  menuButton: {
    padding: 8,
    borderRadius: 8,
  },
  pressedMenu: {
    backgroundColor: "#163a6b",
  },
  profileButton: {
    padding: 8,
    borderRadius: 8,
  },
  pressedProfile: {
    backgroundColor: "#163a6b",
  },
  menu: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: "#f9f9f9",
    paddingVertical: 20,
    paddingHorizontal: 16,
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    zIndex: 1000,
  },
  closeButton: {
    fontSize: 20,
    color: "#E6007E",
    textAlign: "right",
    marginBottom: 16,
  },
  menuItem: {
    fontSize: 18,
    fontWeight: "500",
    color: "#1E4F91",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#E6007E",
  },
  body: {
    padding: 16,
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  tile: {
    width: "100%",
    height: "40%",
    backgroundColor: "#f2f2f2",
    padding: 20,
    borderRadius: 12,
    marginBottom: 16,
    alignItems: "center",
    justifyContent: "center",
    elevation: 3,
    shadowColor: "#E6007E",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  pressedTile: {
    backgroundColor: "#e6e6e6",
  },
  tileText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#1E4F91",
    textAlign: "center",
  },
});
