import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F0F4FF",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#1E4F91",
    paddingVertical: 15,
    paddingHorizontal: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#FFFFFF",
  },
  menuButton: {
    fontSize: 24,
    color: "#ffffff",
    fontWeight: "bold",
    padding: 10,
    borderRadius: 12,
    backgroundColor: "#E6007E",
    shadowColor: "#E6007E",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.4,
    shadowRadius: 4,
    elevation: 4,
  },
  profileButton: {
    borderRadius: 20,
    padding: 10,
    backgroundColor: "#E6007E",
  },
  pressedProfile: {
    opacity: 0.7,
  },
  pressedMenu: {
    opacity: 0.7,
  },
  body: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    gap: 10,
    backgroundColor: "#EAEAF5",
    padding: 20,
  },
  menu: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.85)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 5,
    paddingHorizontal: 20,
  },
  closeButton: {
    fontSize: 24,
    color: "#FFFFFF",
    marginBottom: 30,
  },
  menuItem: {
    fontSize: 20,
    color: "#FFFFFF",
    marginVertical: 12,
  },
  tile: {
    backgroundColor: "#ffffff",
    paddingVertical: 18,
    paddingHorizontal: 30,
    marginVertical: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#E6007E",
    shadowColor: "#E6007E",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 5,
    elevation: 5,
    width: "95%",
    height: "20%",
    justifyContent: "center",
    alignItems: "center",
  },
  tileText: {
    color: "#1E4F91",
    fontSize: 24,
    fontWeight: "bold",
    textAlign: "center",
  },
  pressedTile: {
    backgroundColor: "#D8DCE5",
  },
});
